ATK: 10
ATK_ENERGY_DEMAND: 1
PISTOL: 15
PISTOL_ENERGY_DEMAND: 2
DEF: 5
DEF_ADD: 5
ENERGY: 1
BLOOD: 10
BIG_DEF_ADD: 10
BIG_DEF_ENEGY_DEMAND: 2
ACCUM: 1
ACCUM_DEF_LOSS: 3
DEADLY_ACCUM: 3
DEADLY_DEF_LOSS: 5

